"""Added title column to Post model

Revision ID: 333fe696d407
Revises: de8c92050a4f
Create Date: 2024-05-18 12:00:48.404615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333fe696d407'
down_revision = 'de8c92050a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=False))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
